In [1]:
import numpy as np

In [3]:
A= np.random.randint(1,10,size=(3,3))
B= np.random.randint(1,10,size=(3,3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[5 9 8]
 [7 3 7]
 [7 5 7]]
Matrix B:
 [[1 7 2]
 [7 8 9]
 [4 7 7]]


In [4]:
# Addition
print("A + B:\n", np.add(A, B))

# Subtraction
print("A - B:\n", np.subtract(A, B))

# Multiplication
print("A × B:\n", np.dot(A, B))

# Transpose of A
print("Transpose of A:\n", np.transpose(A))

A + B:
 [[ 6 16 10]
 [14 11 16]
 [11 12 14]]
A - B:
 [[ 4  2  6]
 [ 0 -5 -2]
 [ 3 -2  0]]
A × B:
 [[100 163 147]
 [ 56 122  90]
 [ 70 138 108]]
Transpose of A:
 [[5 7 7]
 [9 3 5]
 [8 7 7]]


In [ ]:
det_A= np.