In [1]:
import numpy as np

In [2]:
marks = np.random.randint(0,101, size=(50,5))
print("marks:\n",marks)

marks:
 [[99 85 27 52 60]
 [56 85 94  3 57]
 [80 79 14 42  3]
 [46 18 37 31 80]
 [47 24 79 31 50]
 [77 53 50 40 71]
 [69 28 73  1 19]
 [67 98 11 54  2]
 [34 74 56 79 56]
 [54  2 92 15 49]
 [56 34 53 92 57]
 [19 64 29 84 96]
 [47  8 14  2 30]
 [48 93 12 24  5]
 [21 51 15 37  6]
 [34 98 46 85 37]
 [42 78 60 24 32]
 [21 19  2 58 85]
 [43  8 46 97 75]
 [99 50 34 17 82]
 [25 43 31 68 87]
 [ 6 10 13 19 54]
 [98 26 71  0  2]
 [95 14 81 86 20]
 [ 7  3 80 29 77]
 [26 24 42 21 48]
 [75 77 16 53 94]
 [40 56 52 25 25]
 [15 41 96 73 11]
 [33 36 13  2 36]
 [50  4 33 74 64]
 [96 31 88 41 10]
 [44 79  8 98 73]
 [76  9 21 92 72]
 [39 85 25 21 33]
 [30 84 57 84 87]
 [95 84 74 43 35]
 [13 24 17 46 46]
 [85 20 11 52 84]
 [31  9 60 17 50]
 [98 97 59 90 27]
 [14 72 39 31 82]
 [96  1 49 31 23]
 [ 6 17 26  7 44]
 [26 88 47 53 50]
 [30 49 56 74 90]
 [91 98 19 18 26]
 [59 34  3 87  8]
 [63  9 14 77 59]
 [49 70 23 92 85]]


In [3]:
avg_per_subject= np.mean(marks,axis=0)
print("AVERAGE MARKS OF EACH STUDENT IS:",avg_per_subject)

AVERAGE MARKS OF EACH STUDENT IS: [51.4  46.86 41.36 47.44 49.08]


In [4]:
highest= np.max(marks,axis=0)
lowest= np.min(marks,axis=0)
print("Highest marks per subject:", highest)
print("Lowest marks per subject:", lowest)

Highest marks per subject: [99 98 96 98 96]
Lowest marks per subject: [6 1 2 0 2]


In [8]:
total_marks = np.sum(marks,axis=0)
avg_total= np.mean(marks,axis=0)
above_avg_students = np.where(total_marks > avg_total)
print("Students scoring above average:", above_avg_students[0])

Students scoring above average: [0 1 2 3 4]


In [9]:
toppers= np.argmax(marks,axis=0)
for i in range(5):
    print(   print(f"Topper in Subject {i+1}: Student {toppers[i]}"))

Topper in Subject 1: Student 0
None
Topper in Subject 2: Student 7
None
Topper in Subject 3: Student 28
None
Topper in Subject 4: Student 32
None
Topper in Subject 5: Student 11
None
